name: build js project
on: push

jobs:
  my-job:
    name: æ‰“åŒ…è¿è¡Œé¡¹ç›®
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository ğŸ›ï¸
      uses: actions/checkout@v2.3.1 
          
    - name: npm install, build ğŸ¤£
      run: |
        npm -v && node -v && node index.js
        npm install 
        npm run build 
     
            
