name: sui test github action
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Before Checkout ğŸ›ï¸
      uses: actions/checkout@v2.3.1 

    - name: Step1 ----- Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

    - name: Step2 ----- æ‰“å°æ—¶é—´è°ƒè¯•æ¨¡å¼
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
          date 
